### ISSUE TITLE
Remove nestedset dependency

### ISSUE THREAD

**Issue by JN-Jones** [mybb/mybb2#148]
The only part of it we're using is the node functionality (parent_id) which can easily be added ourself. To remove some overhead we should remove the library and write our own trait instead.

**Comment by Matslom** [comment]
>The only part of it we're using is the node functionality (parent_id) which can easily be added ourself.

We are using only this one feature? 
If we will remove `left` and `right` id:
1. How we will handle forum order?
2. How to handle forums in forum in category
- category
 --- forum
   ----- subforum
   ----- subforum
   ----- subforum

Also we need some stuff to create, order or remove forums from ACP.

It is true that nestedset dependency have more features than we need but there are some ready to use. We can make our own trait using some methods from this dependency (MIT license).

**Comment by euantorano** [comment]
At the minute, those are the only features we are using. Ordering can be solved with an `order INT DEFAULT 0` column.

Nested sets has some nice features, but from what I remember it doesn't generate very nice queries (this might have changed - we are using a very old version).

**Comment by Matslom** [comment]
Yep, for that moment the queries are ugly. 
There are planned subforums like in 1x, right? So anyway we must add two columns: one for order, second for flag forums as parent (for subforums feature).

Ok then, I will remove this package and take up this ugly queries.

**Comment by euantorano** [comment]
Yep, that's the plan :)
