### ISSUE TITLE
Changing URL structure

### ISSUE THREAD

**Issue by euantorano** [mybb/mybb2#167]
The current url structure follows the format `<type>/<slug>.<id>`. I propose changing this structure to `<type>/<id>/<slug>`. This change is proposed due to the issues the current structure causes with things like dots in usernames.

This change is pretty minimal, requiring only a change to the `routes.php` file due to our use of built in functions to build URLs.

**Comment by Matslom** [comment]
Whether [these](https://github.com/mybb/mybb2/blob/3928bd2f06b430a374937af9e7b42d89d523f602/app/Http/routes.php#L48-L54) links also shouldn't be changed to new structure?

**Comment by euantorano** [comment]
Yep, I missed those - nice catch!

**Comment by JordanMussi** [comment]
I prefer `<type>/<id>/<slug>`.

On should it be customisable:
I see a lot of forums don't move to the basic SEF URLs MyBB 1.x provides (the `<type>-<id>.html` structure). So I imagine most won't be customising this, those that do should be experienced enough to edit the Routes file...

**Comment by euantorano** [comment]
@JordanMussi so basically what it's changing to? :wink: 

They will be customisable once I finish migrating all the views across to using hashes rather than arrays to build links.

**Comment by JordanMussi** [comment]
@euantorano Yeah, fool's on me for not checking the code before commenting! :blush:

Looking at the date on this I should have known to make sure!

**Comment by euantorano** [comment]
@JordanMussi Yep, this was the original proposal (before we were even public). I've changed most of the links and everything across, but there are still a few broken links left.

**Comment by Matslom** [comment]
I fixed most of broken links. Tomorrow I will make PR.
