### ISSUE TITLE
Cannot use MyBB\Core\Database\Models\Topic as Topic because the name is already in use

### ISSUE THREAD

**Issue by JN-Jones** [mybb/mybb2#173]
As mentioned already here: https://github.com/mybb/mybb2/pull/120#discussion_r29245089

**Comment by xaoseric** [comment]
@euantorano probably should change the Presenter classes to have proper naming conventions to avoid future issues?

**Comment by euantorano** [comment]
Yeah, I've suggested that before. Would make a lot more sense.

**Comment by JN-Jones** [comment]
Anything against renaming them to XyPresenter?

**Comment by euantorano** [comment]
Sounds good to me.

**Comment by JN-Jones** [comment]
Apparently this has already been fixed by @JoshHarmon without a PR. Closing.
