### ISSUE TITLE
 Declaration of MyBB\Auth\AuthManager::callCustomCreator() should be compatible with Illuminate\Auth\AuthManager::callCustomCreator($name, array $config)  

### ISSUE THREAD

**Issue by adiantek** [mybb/mybb2#180]
When "composer install" and "php artisan vendor:publish":
  [ErrorException]                                                                                                                                          
  Declaration of MyBB\Auth\AuthManager::callCustomCreator() should be compatible with Illuminate\Auth\AuthManager::callCustomCreator($name, array $config)

**Comment by euantorano** [comment]
Hi, this is a known issue. The auth package is being rewritten to work.

**Comment by adiantek** [comment]
Which commit is fully compilable and runnable?

**Comment by euantorano** [comment]
There isn't currently a working version. Past commits do work, but I can't point to a specific one. The problem was introduced by a change in the Laravel framework.
