### ISSUE TITLE
URLs not adapting to route.php changes

### ISSUE THREAD

**Issue by Nik101010** [mybb/mybb2#184]
Posting this here because there is no bug forum available for 2.0 ... 

There are several links / forms in the templates, where the url is not generated correctly, because the order of url parameters is hardcoded and not generated based on th
e route parameter keys. 

e.g. 
`url_route('user.profile', [user.name, user.id])`
instead of
`url_route('user.profile', {'slug': user.name, 'id': user.id})`

This leads to several dead links currently, because the url structure was changed and leads to an [implemented? feature](http://community.mybb.com/thread-175652-page-2.html) not working correctly.

Occurences of wrong link generation: 
- [x] resources/views/member/online.twig 
- [ ] resources/views/search/result_posts.twig 
- [ ] resources/views/topic/polls.twig 
- [ ] resources/views/topic/reply.twig 
- [x] resources/views/conversation/index.twig 
- [x] resources/views/moderation/queue.twig 
- [x] resources/views/member/list.twig 
- [ ] resources/views/post/quotes.twig 
- [x] resources/views/conversation/preview.twig 
- [ ] resources/views/topic/preview.twig 
- [x] resources/views/topic/edit.twig 
- [x] resources/views/account/dashboard.twig 
- [ ] resources/views/post/likes.twig 
- [ ] resources/views/polls/create.twig 
- [ ] resources/views/polls/edit.twig 

and I propably missed some ...

**Comment by euantorano** [comment]
Yeah, this is a known issue that's just taking me a while to tackle as I have to filter through every view to try and find them. Feel free to open a pull request if you get a chance :smile:

**Comment by Nik101010** [comment]
I was pretty sure this is a known issue, but I could not find any list of known issues :joy:

**Comment by euantorano** [comment]
Yeah, it's a hand written list sat on my desk right now ;)

**Comment by Nik101010** [comment]
Okay - no one is working on that one currently ... Hopefully my regex worked - 35 occurences for links - I start fixing them :joy:
Maybe you find some time to make your list available to the public ^^ would make things easier ^^ 

(fyi: regex I used `url_route\('.*',.*\[.+\)`)

**Comment by euantorano** [comment]
Looks right to me. I'll try get a chance to write them up as issues on this repository this week or next.
