### ISSUE TITLE
Search

### ISSUE THREAD

**Issue by Hackmastr** [mybb/mybb2#203]
``` php
ReflectionException in Container.php line 798
Class MyBB\Auth\Contracts\Guard does not exist
```

URL: /search

**Comment by euantorano** [comment]
Yep, this is a known issue due to the auth package rewrite.

**Comment by JN-Jones** [comment]
Has this been fixed @euantorano

**Comment by euantorano** [comment]
Possibly, I'll have to check.

**Comment by JN-Jones** [comment]
There seems to be some kind of issue with the route. It seems to create a request in the `searchlog` table and throws errors if the validation rules aren't matched but it doesn't seem to find the result later on and throws a `HttpNotFoundException`. Haven't debuged it yet but it may be related to the original issue.

**Comment by euantorano** [comment]
Interesting, do you want to try and debug/fix this whilst I work on the JS?

**Comment by JN-Jones** [comment]
If I can find the cause for this :P

**Comment by JN-Jones** [comment]
Ok, issue found and fixed^^

**Comment by premiumcuyuz** [comment]
Good job @JN-Jones

**Comment by euantorano** [comment]
I'm re-opening this for now as we need to rename the column everywhere. When the PR is merged, this issue will close automagically.
