### ISSUE TITLE
[Bug] Error on showing likes as Guest

### ISSUE THREAD

**Issue by Hackmastr** [mybb/mybb2#204]
The topic page is rendered, but it shows this error:

```php


Whoops, looks like something went wrong.
1/1 FatalErrorException in RenderLikes.php line 90: 
Call to a member function getAuthIdentifier() on null in RenderLikes.php line 90
```

*hope im not flooding this*

**Comment by euantorano** [comment]
Thanks for the report, that's definitely an issue.

**Comment by daoanhvuacc** [comment]
I'm still got this issue when user try to do logout function.

FatalErrorException in LogsoutGuard.php line 68:
Call to a member function getAuthIdentifier() on null

**Comment by euantorano** [comment]
That's a slightly different error, due to the user being null. I will need to investigate what might cause that.
