### ISSUE TITLE
Turn off global timestamps in models

### ISSUE THREAD

**Issue by Matslom** [mybb/mybb2#209]
We don't always need update timestamps on update model. Models like users/topics/posts should have turned off timestamps in models. We can trigger this when we need it (e.g edit post/user profile).

**Comment by euantorano** [comment]
They're fairly useful in some places (such as users which IIRC are only edited when editing profiles - could be wrong), but they should be disabled where they don't help.

**Comment by Matslom** [comment]
Yea they useful, but in some places (like users/posts) they are only needed on create and edit content. Now, they are triggered on every session refresh (save location/last visit) and refresh counters (like post num/thread num). You have more places where they are don't help than help.

**Comment by euantorano** [comment]
True. It's easy enough to disable them. I'll create a patch.

**Comment by euantorano** [comment]
Ok, disabled for some key models.

**Comment by JordanMussi** [comment]
I assume that #210 fixed this.
