### ISSUE TITLE
No class is registered

### ISSUE THREAD

**Issue by aa6my** [mybb/mybb2#216]
No class is registered for content type 'forum'
/vagrant/htdocs/mybb2/app/Permissions/PermissionChecker.php#86

Any idea to solve this one?

**Comment by euantorano** [comment]
Hi,

Interesting. Where do you get this error? Have you ran all of the migrations (`php artisan migrate`)?

**Comment by aa6my** [comment]
yes, already migrate. php artisan migrate.

**Comment by euantorano** [comment]
Hi,

What is the URL of the page? That might help me narrow the cause down. Unfortunately I'm at work at the minute so I can't do a lot to try and fix it until later.

**Comment by aa6my** [comment]
http://localhost/mybb2/

using vagrant without homestead

**Comment by euantorano** [comment]
Very interesting. I'll have to look into this, as I've never seen it happen on the index page. Thanks for the report!

**Comment by aa6my** [comment]
@euantorano welcome

**Comment by aa6my** [comment]
Everything fixed
php artisan migrate
php artisan db:seed
