### ISSUE TITLE
User page

### ISSUE THREAD

**Issue by chack1172** [mybb/mybb2#221]
I'm trying to fix some issues of the repositories.
I fixed user page but I have 2 alternatives.
Which one you are going to use?
![user_1](https://cloud.githubusercontent.com/assets/12584098/16365254/15c86cc8-3bfb-11e6-9383-a3495992ba1e.png)
![user_2](https://cloud.githubusercontent.com/assets/12584098/16365255/15d027f6-3bfb-11e6-9cc1-4c99ed3d866d.png)

**Comment by euantorano** [comment]
Hi, what are the URLs of the pages? I thought there was only meant to be one user page, with different content depending on what profile fields are filled out.

**Comment by chack1172** [comment]
euantorano the url is only one:
mysite.com/public/index.php/user/1/Admin

So the correct page is the second image?

**Comment by euantorano** [comment]
Yes, the second one looks right to me. The two are similar, the only difference is that empty fields are hidden in the second image.

**Comment by euantorano** [comment]
There are some issues with the styling though. The registration date should all be on one line, same with visit date. Paging @justinsoltesz!

**Comment by chack1172** [comment]
Ok, I have another questions.
If I go to Admin profile I see the two profile fields because I set them in the database.
If I go to another user (e.g. Registered) I see the two fields empty, why they aren't hidden?
![user_3](https://cloud.githubusercontent.com/assets/12584098/16375793/8828bea0-3c5d-11e6-9da0-c67a3fa7de62.png)

**Comment by euantorano** [comment]
They should be hidden, there's obviously something missing in the query. This method probably needs to exclude `NULL` profile fields: https://github.com/mybb/mybb2/blob/master/app/Database/Repositories/Eloquent/ProfileFieldRepository.php#L66

I'll have a look tonight after work.

**Comment by chack1172** [comment]
euantorano I only changed function hasForProfileField() in app/Database/Repositories/Eloquent/ because $user is not passes/empty/null.
```

	public function hasForProfileField(User $user=NULL, ProfileField $profileField)
	{
        if($user === NULL)
            return $this->userProfileField->where('profile_field_id', $profileField->id)
                ->count() > 0;
        else
            return $this->userProfileField->where('user_id', $user->getId())
                ->where('profile_field_id', $profileField->id)
                ->count() > 0;
	}
```

**Comment by euantorano** [comment]
Yep, that would also do it. `$user` is null for guests (which will be changed soon).

**Comment by chack1172** [comment]
Why is it null for guests? It shouldn't contain user data we are looking at?

**Comment by euantorano** [comment]
Oops, it shouldn't be null actually. I was thinking `$user` was the currently logged in user. It should never be null for that method. if it is, there's another problem somewhere.

I'm still at work right now so it's difficult for me to debug until I get home unfortunately.
