### ISSUE TITLE
Preparing for Laravel 5.3

### ISSUE THREAD

**Issue by JoshHarmon** [mybb/mybb2#222]
Laravel 5.3 is [currently slated for a release around the same time as Laracon (July 27-29th)](https://laracasts.com/discuss/channels/general-discussion/laravel-53-wish-list), which means it could very well be less than a month away (I assume they'd want to release before the conference). It will only support PHP 5.6+, 7.0+, and HHVM. As we previously decided to track the latest release of Laravel, this kinda matters. I think we should start building now with the system packages that Laravel 5.3 will use so that we're as prepared as we can be before we actually update the framework and deal with that stuff. Then, when 5.3 is released, we should just have to update the dependency in composer.json and work on the things in the "code stuff" section and be up and running quickly (in theory).
# Build/CI
- [x] Since we're moving to Travis CI, we're all good here
# Code
- [ ] Query Builder will now return a Collection instead of an array. Any uses of array functions or array-like interaction should be changed to use Collection stuff.
  - Having trouble grepping to see how badly this will affect us.
  - Potentially affected files:
    - [ ] ./app/Console/Commands/RecountCommand.php
    - [ ] ./app/Database/Repositories/Eloquent/ForumRepository.php
    - [ ] ./app/Database/Repositories/Eloquent/PollVoteRepository.php
    - [ ] ./app/Database/Repositories/Eloquent/PostRepository.php
    - [ ] ./app/Database/Repositories/Eloquent/ProfileFieldOptionRepository.php
    - [ ] ./app/Database/Repositories/Eloquent/ProfileFieldRepository.php
    - [ ] ./app/Database/Repositories/Eloquent/TopicRepository.php
    - [ ] ./app/Database/Repositories/Eloquent/UserProfileFieldRepository.php
    - [ ] ./app/Http/Controllers/ModerationController.php
    - [ ] ./app/Http/Controllers/SearchController.php
    - [ ] ./app/Http/Requests/Account/UpdateProfileRequest.php
    - [ ] ./app/Likes/Database/Repositories/Eloquent/LikesRepository.php
    - [ ] ./app/Presenters/ModerationLogPresenter.php
    - [ ] ./app/Presenters/ProfileFieldGroupPresenter.php
- [ ] Route::controller() will no longer be a thing. There is one call to Route::controller**_s**_() in routes.php  (Source: https://github.com/laravel/framework/pull/10777).
  - [ ] ./app/Http/routes.php:72 (maybe; assuming it will matter)
- [ ] [Collection::whereLoose() method was removed since Collection::where() now supports operators.](http://themsaid.com/laravel-5-3-20160318/)
    Supported: = == === <= >= < > <> != !==
  - [ ] ./app/Database/Models/User.php:132
  - [ ] ./app/Database/Repositories/Eloquent/ConversationRepository.php:221

**Comment by euantorano** [comment]
I have no problem with the upgrade when it happens, but we need to make sure we don't end up using a version that isn't going to work on the majority of hosts. 5.2 requires PHP >5.5.9, 5.3 requires >5.6. We've already hanged our minds a few times about version requirements, so the benefits of the updated framework need to outweigh that IMO.

**Comment by matthijs110** [comment]
There is way more to change. I think it would be easier and better to install a fresh Laravel 5.3 installation and add each functionality bit by bit. Some many things are too old or nearly deprecated.

**Comment by euantorano** [comment]
@matthijs110 We'll evaluate it when 5.3 is released. We managed to upgrade to 5.2 without too much hassle in the end. The Laravel dev usually put out  good upgrade guide.

**Comment by JordanMussi** [comment]
So 5.3 is out... https://laravel.com/docs/5.3/upgrade#upgrade-5.3.0

**Comment by euantorano** [comment]
Yep, I'll be looking at going through the upgrade soon, hopefully this weekend. I also need to try and fix our errors in Travis related to HHVM.

**Comment by JordanMussi** [comment]
HHVM isn't supported by 5.3 so we don't need Travis to check HHMV surely...?

**Comment by euantorano** [comment]
@JordanMussi It's not officially supported, but it would be nice to know that we can run on it to be sure. As far as I know the base 5.3 framework will work just fine on HHVM as it stands.

**Comment by JordanMussi** [comment]
@euantorano Ah fair enough! :grinning:
