### ISSUE TITLE
Timestamps

### ISSUE THREAD

**Issue by chack1172** [mybb/mybb2#223]
In one of the last commits there's a problem.
https://github.com/mybb/mybb2/commit/a33e0fbc2c002dc7069c978e6fd049ab4b7dd68d?diff=unified#diff-e6a42cbe15e7b8610cb2e34cf5f38577

`$timestamps` should be public or we get this error:
Access level to MyBB\Core\Database\Models\User::$timestamps must be public (as in class Illuminate\Foundation\Auth\User)

**Comment by euantorano** [comment]
Yep, @JoshHarmon can you revert that change or shall I create a patch?

**Comment by JoshHarmon** [comment]
Yeah... The code sniffer led me astray there. I'll patch it up.

**Comment by JoshHarmon** [comment]
Fixed in #226
