### ISSUE TITLE
Registrations

### ISSUE THREAD

**Issue by chack1172** [mybb/mybb2#227]
Hi, I "fixed" registrations in my copy but 'created_at' and 'updated_at' aren't inserted. I tried to change the code but the query didn't change.

https://github.com/chack1172/mybb2/commit/4a3b14a140f87e4da300714b1a0089d6568614d5

**Comment by Matslom** [comment]
I fixed one issue here https://github.com/mybb/mybb2/pull/224 
They are protected I think. U need to use timestamps = true for user model.

**Comment by chack1172** [comment]
Will this change add created_at and updated_at?

**Comment by chack1172** [comment]
@euantorano I fixed registration in my copy:

https://github.com/chack1172/mybb2/commit/54acab42e31031bf1654f07f7f11bdfaaddc983c
https://github.com/chack1172/mybb2/commit/e411c3f92fd8abc079add46ad4291fb68a6693e3

**Comment by euantorano** [comment]
Nice one, thanks!
