### ISSUE TITLE
FatalThrowableError in RenderUserProfileLink.php

### ISSUE THREAD

**Issue by Mihu90** [mybb/mybb2#232]
Hello everyone!

My name is Mihai and I am trying to set a local environment for current MyBB 2 sources. I have followed the instructions posted on wiki, but I am still getting an error:
Type error: Argument 1 passed to MyBB\Core\Twig\Extensions\RenderUserProfileLink::renderProfileLink() must be an instance of MyBB\Core\Presenters\User, instance of MyBB\Core\Presenters\UserPresenter given, called in /home/mybbro/public_html/mybb2/mybb2/storage/framework/views/twig/94/94f277c9e42a63e85a60228c53669dbbad0b1884798c419b2428fbb57ab8b6fe.php on line 88

The latest commit included was: 248f964.

I have switched to multiple PHP versions (5.5, 5.6 and 7.0) but didn't succeed to resolve this fatal error.

Thank you.

**Comment by euantorano** [comment]
Hi, this is a bug in the code, and isn't linked to your PHP version. I'll look at it and patch it later today.

**Comment by Mihu90** [comment]
Ok. Thank you :)

**Comment by JoshHarmon** [comment]
Should be fixed in commit 2de2a0ad98e10b121ec3b9a7873ffca2d38cf406
