### ISSUE TITLE
Unexpected Error During Installation.

### ISSUE THREAD

**Issue by chope1** [mybb/mybb2#247]
I got this error after running 
`Composer Install`
PHP Parse error:  syntax error, unexpected ':', expecting ';' or '{' in /var/www/..../mybb/app/Widgets/Registry.php on line 87

  [Symfony\Component\Debug\Exception\FatalErrorException]
  syntax error, unexpected ':', expecting ';' or '{'

**Comment by euantorano** [comment]
Hi,

Which version of PHP are you running (you can find out by running `php -v` at the command line). MyBB 2.0 requires PHP 7.0 as it makes use of scalar type hints and return hints.

**Comment by chope1** [comment]
PHP 5.5.9
Wasn't aware Mybb2 requires PHP 7, shame I cannot upgrade he existing one because my forum Mybb 1.8 is running on it with many plugins which will probably break it.
I will have to get another instances to with fresh PHP 7 installation.
Thanks.

**Comment by euantorano** [comment]
Hi, MyBB 2.0 is not ready to run on a live forum anyway, and there is not currently a way to upgrade from 1.8.

**Comment by chope1** [comment]
I know, not trying to upgrade from 1.8. I am running the test separately, the upgrade I mean is PHP not Mybb. Thanks.

**Comment by euantorano** [comment]
Ah, fair enough!
