### ISSUE TITLE
Add 2FA USB Support

### ISSUE THREAD

**Issue by LiveChief** [mybb/mybb2#256]
Can u guys add a feature where you can lock your account with a USB (FIDO U2F Security Key) so its extra layer of security since hackers are now social engineering phone companies to get a copy of your sim card.
More Info On This Here: https://www.youtube.com/watch?v=LlcAHkjbARs

**Comment by euantorano** [comment]
Hi,

Suggestions should be made on the forum please, allowing the community to discuss them. 

Thanks!
