### ISSUE TITLE
Anti-IPLogger

### ISSUE THREAD

**Issue by adiantek** [mybb/mybb2#260]
Will be avaiable anti-iplogger? For example, when user add [img], MyBB will be download with timeout to set and maximum size and It will be stored on server, like spigotmc.org has it.

PS. This is not issue, it's suggestion.

**Comment by JoshHarmon** [comment]
IPs aren't all that important 99% of the time. I'd be more worried about cookies getting set than anything else.

Multiple issues with the "simple" implementation of this:
 
- Disclosure of server IP when fetching the image
- Storage space is the limiting factor on many hosting accounts. This could eat that up really quickly.

However, I do agree that having, for example, better compatibility with proxies like Camo (which we use with community.mybb.com) could mostly solve this problem. However, this requires a competent server admin to maintain the system, while most of the MyBB user base isn't.

**Comment by adiantek** [comment]
If you have forum for server game (for example minecraft server), IP shouldn't be avaiable for other users. It could be simple option in MyBB ACP.

**Comment by marktopper** [comment]
@adiantek: I think this is better as a plugin.

**Comment by Devilshakerz** [comment]
MyBB 2.0 will support resource proxies: https://community.mybb.com/thread-191635.html
It's possible that we'll also include an internal proxy script for setting up secure boards quickly and for those without heavy traffic.

**Comment by LiveChief** [comment]
dont worry about ip nor cookies if you are really that worried use https://tails.boum.org/ its a OS if you dont want to go that far use https://www.torproject.org/ dont want to use tor? use https://openvpn.net/ dont want to use vpn? use a proxy https://www.uproxy.org/


All of the projects that i posted are OPEN-SOURCE

**Comment by katosdev** [comment]
Based on the answers by @Devilshakerz and @LiveChief I will be closing this issue.
