### ISSUE TITLE
Open Up Wiki

### ISSUE THREAD

**Issue by LiveChief** [mybb/mybb2#261]
Hey can u please open up the wiki section i have afew changes in mind
i want to add a couple of new pages

**Comment by euantorano** [comment]
Hi, the wiki was closed down after some users were making spam edits. 

What changes are you wanting to make?

**Comment by LiveChief** [comment]
i want to add some new pages to it and edit the installation so there is a step by step on how someone does it so its much easier for them to install, now someone needs to know what they are doing to install it but i want to make it so even a 5 year old can copy and paste the commands to their VPS and install it

**Comment by euantorano** [comment]
Hi,

I'm opening the Wiki up for this repository for now, but we will monitor it for spam edits and could end up shutting it again.

Regarding the install process, once MyBB 2.0 goes gold, there will be a proper installer GUI much like in 1.8 that will make installation as easy as you suggest. We're not quite at that stage yet though.

**Comment by LiveChief** [comment]
i made some changed, will make alot more changes when i get back from class

**Comment by euantorano** [comment]
Ok, thanks.

**Comment by LiveChief** [comment]
yo can i add a system checker so it will check if the minimum requirements for mybb2 to work?

**Comment by euantorano** [comment]
Hi,

There's one that already exists that has been posted on the forum. I'd rather not have an official one in case requirements change (though they shouldn't).

**Comment by LiveChief** [comment]
can u please post a url to it

**Comment by LiveChief** [comment]
New readme.md
https://ghostbin.com/paste/amw8m

**Comment by euantorano** [comment]
Hi,

Please see here: https://community.mybb.com/thread-190359.html

Regarding the README, is the only change the bottom section about support? If so, we don't want to add that in case people think that means we'll provide support for 2.0 - which we will not do until it is officially released.

**Comment by LiveChief** [comment]
hey i am not talking about like someone downloading mybb, plugin and checking i am talking about like uploading 1 php file to their host to check if it works or not

**Comment by euantorano** [comment]
Hi,

I’d still rather not add it to this repository as this should just be the core code. Perhaps add a wiki page with the code required? Or we can create a new repository that does all the checking. Jordan is a staff member so I’m sure he’d be happy to add his code to a new repository.

**Comment by LiveChief** [comment]
lol not this one, i am talking about like uploading it to somewhere else and like if they want to check it they wget it to their systems, it wont be on repository

**Comment by euantorano** [comment]
Ah, yes that would be fine. I've contacted Jordan and asked if he'll be happy to add his code to a new repository that can be easily checked out and ran. Thanks for the suggestion!

**Comment by LiveChief** [comment]
in the wiki section under installation should i only add the required packages or some mod packages too?

**Comment by euantorano** [comment]
Only the required packages for now. The idea is to just help developers get a development environment live.

**Comment by LiveChief** [comment]
will mybb 1.0 and 2.0 have same logo?

**Comment by euantorano** [comment]
I think the plan is to possibly update the font, but we’re not fully decided yet.

**Comment by LiveChief** [comment]
updated read.me
