### ISSUE TITLE
Plugin Auto Download And Install

### ISSUE THREAD

**Issue by LiveChief** [mybb/mybb2#262]
Hey i was thinking of like something along the line of wordpress where people can click one button and it will automatically download and install plugins that are uploaded in MyBB Mods

**Comment by euantorano** [comment]
Pleas make feature suggestions on the forum.

This has already been discussed and ruled out for now due to the security risk - should the MyBB servers become compromised, all forums could be via a bogus plugin update.

**Comment by LiveChief** [comment]
how about something like you upload a plugin as a zip and it automatically puts the files in place, there are alot of plugins out there with 50+ files on different locations

**Comment by euantorano** [comment]
That is more likely to happen.

Plugins will also be installable via Composer too, so there won’t be that problem of files being spread about all over the place.
