### ISSUE TITLE
Any Plan for API?

### ISSUE THREAD

**Issue by mtangoo** [mybb/mybb2#270]
The world is going mobile. While its great to have responsive design, forum owners will want to have streamlined Mobile Apps. having mobile app will make MyBB more of the choice because of mobile power it will be providing.

That being said, is there any plan to incorporate Rest API? At least for basic, non admin functionalities?

Sorry if it is already written somewhere. I could not find any discussion on this.
Cheers!

**Comment by Matslom** [comment]
There are plans for API. https://community.mybb.com/thread-191930-post-1218363.html#pid1218363

**Comment by euantorano** [comment]
This is planned, but not yet implemented.

**Comment by mtangoo** [comment]
Wow that sounds great. I hope MyBB2 comes soon
Cheers!
