### ISSUE TITLE
FatalErrorException in ProfileFieldPresenter.php line 19

### ISSUE THREAD

**Issue by AlexL777** [mybb/mybb2#294]
Hello Developers,

I wanted to see your work live and installed the board. Puh .... it was very bad if I only knew that the database InnoDB and utf8mb4 unicode must be. Simply so with UTF8 it does not fold, because the number of bytes for the API KEY is 1000 bytes and that did not work then unfortunately.

I have tried a few things and have `/account/profile` this error.

```
FatalErrorException in ProfileFieldPresenter.php line 19:
Declaration of MyBB\Core\Presenters\ProfileFieldPresenter::getValidationRules(): array must be compatible with MyBB\Core\Form\RenderableInterface::getValidationRules(): string
```

If you can help me and I know that it can only be a test installation. I was just curious about what you do: smile:

**Comment by euantorano** [comment]
Hi,

This is a known bug on the current code that I'll be fixing when I get back from my holiday. 

The encryption key issue is definitely annoying, I need to look again at what we can do to fix that.

**Comment by AlexL777** [comment]
Thanks,
I am very happy to help something, because MyBB 2.0 interents me very much as an admin.
