### ISSUE TITLE
Good Job!

### ISSUE THREAD

**Issue by wherkamp** [mybb/mybb2#314]
Good Job on the project, keep it going!

**Comment by pixiuPL** [comment]
Just the opposite, but peace :)

**Comment by wherkamp** [comment]
@pixiuPL I don't think the project is dead?

**Comment by fluxtion** [comment]
> why this project is even alive?

I'm going to optimistically assume that your poor grasp of the English language gave your message unintended connotations.

It is alive because we still work on it.

**Comment by 1e4** [comment]
Project isn't dead at all, as to

> why this project is even alive?

Why are you even here?
Why do you even take the time to comment crap?
And looking at your profile, just makes you sound like a pathetic troll

**Comment by WildcardSearch** [comment]
People, this is a software repository. Lets keep it professional.
