### ISSUE TITLE
Alpha 1 Warning System

### ISSUE THREAD

**Issue by wpillar** [mybb/mybb2#47]
**Features**
- [x] Warn a user
- [x] Warn a user for a particular piece of content (post, topic etc)
- [x] Configurable presets for warning points and reasons
- [x] Warn using a preset, or custom reason and points

**Comment by Matslom** [comment]
If noone is working on it, I will try implement this.

**Comment by euantorano** [comment]
Nobody is working on it as far as I know, so feel free :)

**Comment by euantorano** [comment]
@Matslom Before starting this, we should probably discuss what we want out of the warning system and how it should work/look. If you've got some ideas, feel free to contact me on here, on Discord, or on the forums (I'm `Euan T` on the forums) and we'll discuss it.

The first step would be working out the database structure and the required models/repositories.

**Comment by Matslom** [comment]
Long post, sorry for my poor english.
I think that we should give warning system more freedom for plugins, as in the "Like system". I.e. content_type (to specify model (Post/Topic)) and content_id.
For now I have one table.
```php
			$table->increments('id');
            $table->unsignedInteger('user_id');
            $table->unsignedInteger('content_id');
            $table->string('content_type');
            $table->unsignedInteger('issued_by');
            $table->string('reason');
            $table->integer('points');
            $table->timestamps();
            $table->timestamp('expires_at');
            $table->boolean('expired')->default(false);
            $table->timestamp('revoked_at')->nullable();
            $table->unsignedInteger('revoked_by')->nullable();
            $table->string('revoke_reason')->nullable();
```

Do we need column for notes?

Acknowledge with warning - https://community.mybb.com/thread-195011.html
I think that we can just block forum and show last and all active warnings for acknowledge. For that feature we need one bool column in user table. From now we don't need PM's for sending information about warnings.

Warnings levels:
I don't know how we will implement restrictions. Maybe, we can just give ability to select group (role) in which user will be move after overstep specified level. This will give a lot of possibilities to restrict user.

Also some settings:
- max points (default 10)
- lack of ideas for now

**Comment by euantorano** [comment]
Looks good, but revoke reason should maybe be text?

**Comment by euantorano** [comment]
Nice one, thanks!

**Comment by Matslom** [comment]
I have some idea. 
Saving snapshot warned content. Example:
You warn user for post and actual post content is forever saved in warn as snapshot for future preview.
Often posts are deleted after warning user and you don't have any preview.

**Comment by euantorano** [comment]
Makes sense to me.

**Comment by Matslom** [comment]
Hi guys. I have a little problem.
How should I deal with different types of content (Posts/Topics/Users/other extended by plugins)?
Should I create a bunch of classes (post/topic/user) with informations about this type of content and then call it when creating a warning by url:
`moderation/warn/{user}/{content}/{contentId}` so for example: 
`moderation/warn/1/post/2` will include post class
`moderation/warn/1/gallery/4` will include gallery class added by plugin author.

So I'm looking for a way to handle some information about different contents, like: 
"is this content should be saved as snapshot?",
"what name have column with content to save?",
"how to render saved content?"

Maybe should I do it in other way? What do you think?

**Comment by Holyphoenix** [comment]
Not a PHP master here, I tend to work on Java or C# most of the time.  But couldn't you create an interface called "warnable" that people could implement on their object which they want to be warnable?  And on that interface define a method that returns the snapshot data and a method that returns a type for that data as text, image, etc?  Then if someone has a plugin that hooks into the warn system, it should look at that objects methods rather than having to create a separate class for each object that is warnable.

**Comment by euantorano** [comment]
I would think something like the following should work:

- `MyBB\Core\Warnings\Manager` - a manager class that is used to manage warnings and warning content types.
- `MyBB\Core\Warnings\WarnableContentInterface` - an interface that can be implemented for models (content types) that describes the `preview` (e.g.: `getWarningPreviewContent()` which gets the content and `getWarningPreviewView()` which gets the name of the view/template to use to render the warning)
- Content types would then be registered with a short name (e.g.: `post`, `pm`, etc) and a callback to retrieve the instance being warned (the model, which implements `MyBB\Core\Warnings\WarnableContentInterface`)

I think that would be the best approach. The actual warning table would have a polymorphic relationship to the warned item too hopefully.
